function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Survivors in the Vomit Zone may", effect = "Heal all Injury Levels at 1 Hit Location of their choice"}})
end

function woundEffect()
	Global.call('addBroadcast', {"wound_reaction", {gear = "☠☠☠ Perform Retch ☠☠☠", effect = ""}})
end
function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end