function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Full move the monster towards the farthest board edge and turn to face attacker", effect = ""}})
end

function woundEffect()
  Global.call('addBroadcast', {"wound_reaction", {gear = "Full move the monster towards you ~ Then if adjacent ~ Suffer Knockback 10", effect = ""}})
end

function failureEffect()

end

function reflexEffect()
end

function addStatModifier()
end
