function criticalWoundEffect()
	local obj = getObjectFromGUID(Global.getTable('tokSpawn').pos_dmg.guid)
	local var = ""
	obj.getVar("phase")
	obj.setVar("phase", var)
	obj.call("spawn_token")
	Global.call('addBroadcast', {"crit", {gear = "The Kingsman gained a (+1) Damage Token", effect = ""}})
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
