function criticalWoundEffect()
     Global.call('addBroadcast', {"crit", {gear = "Persistent Injury ~ Jaw Paralysis ~ Keep in Play", effect = ""}})
end

function woundEffect()
    Global.call('addBroadcast', {"wound", {gear = "\u{2620}\u{2620}\u{2620} Perform Retch \u{2620}\u{2620}\u{2620}", effect = ""}})
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end