function criticalWoundEffect()
  Global.call('addBroadcast', {"crit", {gear = "Persistent Injury ~ Crippled Vines ~ Keep in Play", effect = "", effect2 = ""}})
  Global.call('addBroadcast', {"crit", {gear = "You are the Axe King! ~ Gain (+1) Permanent Strength", effect = "", effect2 = ""}})
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
