function criticalWoundEffect()
    Global.call('addBroadcast', {"crit", {gear = "If you have 3+ Courage ~ Gain (+1) Survival", effect = ""}})
    Global.call('addBroadcast', {"crit", {gear = "", effect = ""}})
    Global.call('addBroadcast', {"crit", {gear = "The Dung Beetle Knight and you both suffer Knockback 5", effect = ""}})
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end