function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Turn the Gorm to face the opposite board edge", effect = ""}})
	Global.call('addBroadcast', {"crit", {gear = "♘ Full move forward in a straight line ♘", effect = ""}})
	Global.call('addBroadcast', {"crit", {gear = "The Gorm is knocked down!", effect = ""}})
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
