function criticalWoundEffect()
  Global.call('addBroadcast', {"crit", {gear = "Archive any Number of Gates ~ If 5+ are archived, the Tyrant is knocked down", effect = ""}})
end


function woundEffect()
	Global.call('addBroadcast', {"wound_reaction", {gear = "Perform Resonate ~ Targeting the Attacker", effect = ""}})
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
