function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Persistent Injury", effect = "Keep in Play"}})
	self.setPositionSmooth({0.08, 4.34, -14.16}, false, false)
end


function woundEffect()
end

function failureEffect()
	Global.call('addBroadcast', {"failure", {gear = "Perform Basic Action ~ Targeting Attacker", effect = ""}})

end

function reflexEffect()
end

function addStatModifier()
end
-- temple