function criticalWoundEffect()
     Global.call('addBroadcast', {"crit", {gear = "All Survivors in the Vomit Zone gain (+3) Insanity", effect = ""}})
end

function woundEffect()
end

function failureEffect()
    Global.call('addBroadcast', {"wound", {gear = "\u{2620}\u{2620}\u{2620} Perform Retch \u{2620}\u{2620}\u{2620}", effect = ""}})
end

function reflexEffect()
end

function addStatModifier()
end
