function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Attacker gains (+1d10) Insanity", effect = ""}})
	Global.call('addBroadcast', {"crit", {gear = "You may perform Embolden", effect = ""}})
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
	Global.call('addBroadcast', {"reflex", {gear = "Perform Basic Action ~ Targeting the Attacker", effect = ""}})
end

function addStatModifier()
end
