function criticalWoundEffect()
  Global.call('addBroadcast', {"crit", {gear = "You are showered in a sticky substance ~ Remove 1 Bleeding Token", effect = "", effect2 = ""}})
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
  broadcastToAll("A Survivor adjacent to you may spend 1 Survival to cancel the reaction on this location", {1,1,1})
end
