function criticalWoundEffect()
	local obj = getObjectFromGUID(Global.getTable('tokSpawn').neg_spd.guid)
	local var = "startOfMonsterTurn"
	obj.getVar("phase")
	obj.setVar("phase", var)
	obj.call("spawn_token")
end

function woundEffect()
end

function failureEffect()
    Global.call('addBroadcast', {"failure", {gear = "Perform Basic Action ~ Target Furthest Survivor in Range", effect = ""}})
end


function reflexEffect()
end

function addStatModifier()
end
