

function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Persistent Injury ~ Lost Ding Dong ~ Keep in Play", effect = "", effect2 = ""}})
	getMonsterResource(deck, name, params)
	getStatToken()
end

function getStatToken()
	local object = getObjectFromGUID('eb87ec')
	local desc = object.getDescription()
	object.setDescription('end of showdown')
    	object.setScale({0.43, 1.00, 0.43})
			local dmgStat = Global.getTable('dmgStat')
        		table.insert(dmgStat, object.clone({
				position = {-13.19, 4.42, 0.51 + #dmgStat * -1}}))
				Global.call('addBroadcast', {"crit", {gear = "The White Lion gained a (+1) Damage Token", effect = ""}})
    	object.setScale({0.32, 1.00, 0.32})
	Global.setTable('dmgStat', dmgStat)
end

function addStatModifier()
end

--Finds a named card, in a deck, in a zone, then draws it to specified location.
function getMonsterResource(deck, name, params)
	    print("[b]---Items In Zone---[/b]")
		zonesTable = Global.getTable('zones')
		local zone = getObjectFromGUID(zonesTable.deckMonsterResources.guid)
	    local objectsInZone = zone.getObjects()
	    if #objectsInZone == 0 then
	        print("Scripting Zone Empty.")
	    else
	        for _, object in ipairs(objectsInZone) do
	            local name = object.getName()
	            if name == "White Lion Resources Deck" then
					deck = object
					break
	                print("White Lion Resources Deck Found")
	            else
	                print("White Lion Resources Deck Not Found.")
	            end
			end
			if deck == nil then
		        print("No deck was found.")
		    else
		        print("Deck found.")
		        local cardsInDeck = deck.getObjects()
		        for i, card in ipairs(cardsInDeck) do
		            if card.nickname == "Lion Testes" then
					    print("Lion Testes found")
						deck.takeObject({
							guid = card.guid,
							position={7.60, 4.19, -11.03},
							callback="flipCard",
							callback_owner=Global,
						})
						Global.call('addBroadcast', {"crit", {gear = "You gained 1 Lion Testes", effect = ""}})
						break
				end
		            if i == #cardsInDeck then
		                Global.call('addBroadcast', {"crit", {gear = "You already hacked off the Lion's Testes", effect = ""}})
		            end
		        end
		    end
		    print("[b]----------------------[/b]")
		end
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
