function onLoad()
  createButton()
end


function createButton()
  self.createButton({click_function = "goTo", function_owner = self, label = "[ Survivors Return ]",
  position = {0, 0.2, 0}, scale = {0.5, 0.5, 0.5}, width = 5000, height = 1600, font_size = 0,
  color = {0,0,0}, font_color = {1,1,1}, font_size=800})
end

function goTo(object, player)
  local parameters = {}
  parameters.position=  {-61.29, 4.63, 28.73}
  Player[player].lookAt(parameters)
end