function onLoad()
  createButton()
end


function createButton()
  self.createButton({click_function = "callSurge", function_owner = self, label = "Surge",
  position = {0, 0.5, 0}, rotation = {-5, 0 , 0}, scale = {0.5, 0.5, 0.5}, width = 5000, height = 1600, font_size = 0,
  color = {0,0,0}, font_color = {1,1,1}, font_size=800})
end

function callSurge()
	local menuToken = getObjectFromGUID('4825fa')
	menuToken.call("Surge")
end