
--------------------------
--Init
----------------------------
function onLoad()

	self.createButton({
		click_function = 'getConsequences',
		function_owner = self,
		label = '+',
		position = {0.9,0.3,-1.4},
		rotation = {0,0,0},
		width = 150,
		height = 150,
		font_size = 150
	})

function getConsequences()
	getForbiddenDance()
	getSongoftheBrave()
end

--Finds innovation consequences and adds them to the Innovation deck
function getSongoftheBrave(deck, name, params)
	    print("[b]---Items In Zone---[/b]")
		zonesTable = Global.getTable('zones')
		local zone = getObjectFromGUID(zonesTable.deckConsequences.guid)
	    local objectsInZone = zone.getObjects()
	        for _, object in ipairs(objectsInZone) do
	            local name = object.getName()
	            if name == "Consequences" then
					deck = object
					break
	            end
			end
		        local cardsInDeck = deck.getObjects()
					for i, card in ipairs(cardsInDeck) do
					if card.nickname == "Song of the Brave" then
						deck.takeObject({
							guid = card.guid,
							position={-44.15, 4.40, 22.58},
						})
						broadcastToAll("Song of the Brave added to Innovation Deck", {1,1,1})
						break
						end
					end
				end

--Finds innovation consequences and adds them to the Innovation deck
function getForbiddenDance(deck, name, params)
	    print("[b]---Items In Zone---[/b]")
		zonesTable = Global.getTable('zones')
		local zone = getObjectFromGUID(zonesTable.deckConsequences.guid)
	    local objectsInZone = zone.getObjects()
	        for _, object in ipairs(objectsInZone) do
	            local name = object.getName()
	            if name == "Consequences" then
					deck = object
					break
	            end
			end
		        local cardsInDeck = deck.getObjects()
					for i, card in ipairs(cardsInDeck) do
					if card.nickname == "Forbidden Dance" then
						deck.takeObject({
							guid = card.guid,
							position={-44.15, 4.40, 22.58},
						})
						broadcastToAll("Forbidden Dance added to Innovation Deck", {1,1,1})
						break
						end
					end
				end
			end
