
function criticalWoundEffect()
	getStatToken()
end

function getStatToken()
	local obj = getObjectFromGUID(Global.getTable('tokSpawn').neg_mov.guid)
	local var = ""
	obj.getVar("phase")
	obj.setVar("phase", var)
	obj.call("spawn_token")
	Global.call('addBroadcast', {"crit", {gear = "The White Lion gained a (-1) Movement Token", effect = ""}} )
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end

-- knee
