function criticalWoundEffect()
Global.call('addBroadcast', {"crit", {gear = "You gain (+1) Insanity", effect = ""}})
end

function woundEffect()
    Global.call('addBroadcast', {"wound", {gear = "The Kingsman fights dirty spewing acid into your eyes", effect = ""}})
    Global.call('addBroadcast', {"wound", {gear = "If you are within 2 spaces ~ Gain (-2) Accuracy Tokens", effect = ""}})
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
