function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Roll 1d10 ~ On a 5+", effect = ""}})
	Global.call('addBroadcast', {"crit", {gear = "Gain (+1) Courage ~ (+1) Survival", effect = ""}})
end

function addStatModifier()
end

function woundEffect()
end

function failureEffect()
	Global.call('addBroadcast', {"failure", {gear = "Perform Basic Action ~ Targeting the Attacker", effect = ""}})
end

function reflexEffect()
end

function addStatModifier()
end
