function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "Persistent Injury ~ Jaw Paralysis ~ Keep in Play", effect = ""}})
	self.setPositionSmooth({0.08, 4.34, -14.18})
end

function woundEffect()
	Global.call('addBroadcast', {"wound_reaction", {gear = "☠☠☠ Perform Retch ☠☠☠", effect = ""}})
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end