
function criticalWoundEffect()
	Global.call('addBroadcast', {"crit", {gear = "The White Lion gained a (-1) Movement Token", effect = ""}} )
	getStatToken()
end

function getStatToken()
	local obj = getObjectFromGUID(Global.getTable('tokSpawn').neg_mov.guid)
	obj.call("spawn_token")
end

function woundEffect()
end

function failureEffect()
end

function reflexEffect()
end

function addStatModifier()
end
